### PR TITLE
Mini cleanup

### PR DESCRIPTION
**Pull request by Angelfire**
- move `parse` dependency to the top of the module
- cleanup a bit the JSDoc (would be great if some can add the missing information)
- remove `options = options || {};` since `options` already has default value

### CODE REVIEW

**Comment by Angelfire** [comment]
@chrisbottin is anybody able to review PRs?

**Comment by chrisbottin** [comment]
Yes, sorry. Will do now.

**Comment by Angelfire** [comment]
This repo is inactive.

**Comment by chrisbottin** [comment]
Did you see my comments?

**Comment by chrisbottin** [comment]
sorry, looks like I didn't submit my comment made last week

**Pull request closed without merging**
